ocaml-bench/sandmark-nightly

app/apps/sequential_benchmarks.py

This PR aims to resolve https://github.com/ocaml-bench/sandmark-nightly/issues/18
The issue was closed and reopened because the logic that I used to find the intersection did not take into consideration of the order and resulted in an index error when it was in a specific order.
But the PR aims to resolve it, the following image is the result of the changes (which previously resulted in the index error)

fix dataframe intersection order issue

---

Dockerfile

Not sure how this got re-introduced but you don't need the git clone here, it should be using the git clone from ocurrent-deployer.

Use git clone from ocurrent-deployer

---

app/apps/instrumented_pausetimes_parallel.py
app/apps/instrumented_pausetimes_sequential.py

Since the instrumented pausetimes are not currently updated with the latest ocaml 5.0 there should be a way to make the user aware of this. The PR adds this info in the UI

add archive message for instrumented benchmarks

---

app/apps/index.py

https://github.com/ocaml-bench/sandmark-nightly/issues/46 mentions the error on the landing page.
This error was a result of inconsistent usage of separator in finding the sandmark directory resulting in `//sandmark` path.
I replaced usage of `os.path` with `pathlib.Path`
The landing page seems to work fine locally

Fix the landing page error issue

---

app/apps/benchstruct.py
app/apps/parallel_benchmarks.py
app/apps/sequential_benchmarks.py

This PR adds a display function to `app/apps/benchstruct.py` to enable the UI to show the selected benchmarks and their various components - hostname, timestamp, commit id and variant name in a table. This makes reading of long names feasible.
This might be the closest way to know what we are selecting in absence of a tooltip function that displays the component name in streamlit.
The current way in which tooltip for streamlit works is more of an info for the component than for the data inside the component.
so this PR tries to create a table out of selected benchmarks and the table by default has a tooltip display which makes things easier.

Show benchmarks in a table to read the tooltip

---

app/app.py
app/apps/index.py

Instrumented runtime is not used currently, and having those pages is a distraction. This PR hides it.

Hide instrumented runtime pages

---

app/app.py
app/apps/benchstruct.py
app/apps/index.py
app/apps/instrumented_pausetimes_parallel.py
app/apps/instrumented_pausetimes_sequential.py
app/apps/parallel_benchmarks.py
app/apps/sequential_benchmarks.py
app/multiapp.py

The PR backports changes from the Sandmark notebook to the webapp (https://github.com/ocaml-bench/sandmark/pull/351). The code was slightly changed to improve the detection of duplicated variants when trying to normalise the data. 
Also, I ran into issues when trying to edit the files because they use TABs instead of spaces. It is [recommended](https://peps.python.org/pep-0008/#indentation) to use spaces and is the general convention in the Python world. I used [Black](https://github.com/psf/black) to format the files to make the formatting style easily reproducible by everyone working on this codebase.  I made these formatting changes in a separate commit, but didn't make them in a separate PR, since the repo doesn't have any pending PRs, as of now.

Backport changes to normalise function from Sandmark notebook

---

app/apps/benchstruct.py
app/apps/parallel_benchmarks.py
app/apps/sequential_benchmarks.py

I've simplified the convoluted logic to format the benchmark variant name, to fix this bug. I tried to look at the commit history to try to understand why this was introduced, but I couldn't find any history since most of the change seems to have been introduced in a single commit.  So, I may be breaking a requirement of how the version number should be displayed on the UI, but this should work reliably without depending on file names being in a specific format. 
I've also cleaned up some related code that tries to look for the bench files to be shown in the UI for selection, in separate commits.

Fix bench file not found error on production webapp

---

app/apps/benchstruct.py

The parameter `root_dir` was added only in Python 3.10 and causes an error in older versions of Python.

Remove use of root_dir parameter to glob.glob

---

app/apps/sequential_benchmarks.py

8f56a1b33edcfe0b65bb9026518093dce3ef235d over simplified how commit and
variants were formatted previously to fix #56. But, it makes UI dropdown not
usable and useful.
Closes #59

Revert aggressive change to variant & commit formatting

---

app/apps/parallel_benchmarks.py
app/apps/sequential_benchmarks.py
app/apps/utils.py

9188cac05ddfe065783c572260d5c07b8e did not fix the parallel benchmarks UI, and
only fixed the UI for sequential benchmarks. This commit fixes that.
#61 only partially fixed the formatting of variant+commit.

Fix parallel UI to undo the aggressive variant & commit formatting

---

app/apps/benchstruct.py
app/apps/instrumented_pausetimes_parallel.py
app/apps/instrumented_pausetimes_sequential.py
app/apps/parallel_benchmarks.py
app/apps/sequential_benchmarks.py
app/apps/utils.py

This PR does a bunch of preparatory refactoring to simplify the code for getting the selected variant type from the UI. 
The last 3 commits implement functional changes in the UI.
1. Make hostname and date columns much narrower than variant column
2. Remove bench type & stem, show shorter commit hash in dropdown
3. Show a date dropdown instead of timestamp dropdown in the UI when selecting variants
Closes #60

Show dropdown for date instead of timestamp when selecting variants

---

app/apps/benchstruct.py
app/apps/instrumented_pausetimes_parallel.py
app/apps/instrumented_pausetimes_sequential.py
app/apps/parallel_benchmarks.py
app/apps/sequential_benchmarks.py
app/apps/utils.py

#63 changed some of the common utility code like BenchStruct, which would break the pausetimes sequential and parallel apps. This PR makes sure that the new changes are compatible with both these apps, even if they are unused in the UI.

Ensure unused pausetime apps are functional too

---

.github/workflows/copy-successful-builds.yml
scripts/copy-successful-builds.sh
scripts/slack-notify-build-status.sh

The PR adds a script to copy successful builds from testing to main branch, and sets up a GitHub hook that runs when there are changes to the testing branch. This closes #65 
The PR also sends a Slack notification with information about successful and failed builds. This closes #42 
To get the GitHub action to run correctly, the sandmark-nightly repo needs to have a secret called `SLACK_API_URL` added. (I don't have the right permissions to do that). 
Examples of successful runs of the GitHub action can be found [here](https://github.com/punchagan/sandmark-nightly/actions).  This PR itself doesn't trigger any GitHub actions because the action is restricted to trigger only on the `testing` branch.

Automatically copy results for successful builds and notify on Slack

---

app/apps/benchstruct.py
app/apps/parallel_benchmarks.py
app/apps/sequential_benchmarks.py
app/apps/utils.py

As an initial experiment to fix #67 I've added a radio button to allow searching for a benchmark by variant or hostname.  I've used date as the second level of filter in both the cases.
@shakthimaan Let me know if this is good as a first version, or if we should do something different here.

Allow filtering variants to select by hostname or variant name 

---

scripts/copy-successful-builds.sh

76cfc5d7a590772a7967ddf27f2cca692cbbbb7c accidentally deleted the `git push`
command, which broke the copying of successful builds from testing to main.
These changes need to be merged into `testing` once they are merged on `main`.

Fix accidentally deleted push in successful results copy script

---

app/apps/parallel_benchmarks.py

When the sequential run for a benchmark cannot be found, the parallel benchmark
app crashes.  Currently, the fannkuchredux sequential run seems to be
failing.  This commit fixes the crash in the streamlit app.  The problem with
the benchmark itself needs to be fixed, separately, though.
Closes #83

Fix error in parallel app for missing sequential benchmark

---

app/apps/sequential_benchmarks.py

Ensure baseline variant name matches format of variant
f93f5bb3e14701399bb8d14f44887b34b32f50e7 changed the format of the variant to
show hostname in the graphs. This caused an error when trying to add a display
name column because the baseline name was formatted differently. This commit
fixes it.
Closes #89

Fix sequential benchmarks not working

---

app/apps/perfstat.py
app/apps/sequential_benchmarks.py
app/apps/utils.py

This commit simplifies and fixes the `add_display_name` function to work correctly, when the different variants selected have a different set of benchmarks.
It also fixes another issue that is similar to the one fixed by https://github.com/ocaml-bench/sandmark/pull/351where a difference in the list of benchmarks in the two selected variants causes the `normalise` function to crash.

Fix Perfstat app when selected variants have different benchmarks

---

app/apps/utils.py

This seems to happen sometimes with the Perfstat data and the UI crashes due to this. This commit displays an error message instead of the traceback.

Gracefully handle baseline data being empty

---

.github/workflows/production-user-tests.yml
.github/workflows/tests.yml
tests/test_ui.py

We've had a bunch of issues recently reported by our users -- for instance #97, #89, #83, etc.  This PR adds a cron job that runs on GitHub actions and checks the UI for exceptions. Failed builds would be notified on GitHub and not on Slack, but this may be a good first step for us to proactively find issues and fix them, instead of discovering issues only when reported by our users.
(Some runs of this action can be found here: https://github.com/punchagan/sandmark-nightly/actions/workflows/production-user-tests.yml)
The PR also has a few improvements to the Python tests and running them via GH actions.

Run daily UI tests against production as a cron job

---

.github/workflows/copy-successful-builds.yml
scripts/slack-notify-build-status.sh

The <!here> syntax doesn't trigger an @here mention when the text is present in the header section. This commit moves it to a markdown section.

Move @here mention to markdown section from header

---

requirements.txt
tests/requirements.txt

Seaborn got updated to `0.12` automatically and that caused the parallel benchmarks to throw a traceback in the UI for the latest benchmark run where the data for `mergesort` run has NA values.

Fix the versions of dependencies

---

app/validate_run.py

Previously, errors like the following would not be detected, which are now detected and the validation of the log file fails.
```
make: *** [Makefile:228: ocaml-versions/5.1.0+stable.bench] Error 1
```

Detect make errors when validating benchmark logs

---

requirements.txt

The parallel benchmarks app is broken app with Pandas 2.0.0
The failure was detected using the daily production UI test [here](https://github.com/ocaml-bench/sandmark-nightly/actions/runs/4604979824/jobs/8136472315) and can also be seen in the Sandmark nightly UI, [here](https://sandmark.tarides.com/?app=Parallel+Benchmarks&parallel_num_variants=1&parallel_01=20230405&parallel_02=turing_5.1.0%2Btrunk%2Bparallel_20230405_8746939&parallel_find_by=variant&parallel_00=5.1.0%2Btrunk%2Bparallel)

Use a fixed version of Pandas

---

app/pages/status.py

The status page UI test fails on the testing branch, since git doesn't allow fetch and updating a currently checked out branch.  This commit adds a check for the current branch and avoids updating the currently checked out code.

Don't update the testing branch if it's already checked out

---

app/pages/status.py

With the upgrade to Streamlit 1.22.0 in
deb0163fe7a6f18c96348ff8daa569b905cbd79c, the function st.cache is deprecated.

Use st.cache_data instead of st.cache

---

app/apps/index.py
tests/test_index.py

Due to an opam repository bug, some of our log files contained a non UTF-8 character. Our code to find git commit ID from log files was crashing due to this, which this PR fixes.

Fix test get commit id failures

---

tests/requirements.txt

The download process for downloading the latest chromedriver was changed recently, which causes `sbase get chromedriver latest` to install a slightly older version that doesn't work with the latest browser. The newer version of seleniumbase fixes `sbase get` command to fetch the latest driver.
Fixes CI runs like [this](https://github.com/ocaml-bench/sandmark-nightly/actions/runs/6940436726)

Upgrade seleniumbase to latest version
